//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mecanicos
    {
        public int id_mecanico { get; set; }
        public Nullable<int> id_taller_mecanico { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string cedula { get; set; }
        public string fecha_nacimiento { get; set; }
        public Nullable<bool> estatus { get; set; }
    
        public virtual Taller Taller { get; set; }
    }
}
