//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTaller.Conexion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
<<<<<<<< HEAD:ProyectosPersonales/ProyectoTaller/ProyectoTaller/Conexion/Conexion.Context.cs
    public partial class db_TallerEntities1 : DbContext
    {
        public db_TallerEntities1()
            : base("name=db_TallerEntities1")
========
    public partial class db_taller_infotepEntities : DbContext
    {
        public db_taller_infotepEntities()
            : base("name=db_taller_infotepEntities")
>>>>>>>> bf40c2153169e19b211541496eaf1dcd5dbd88f1:ProyectosPersonales/ProyectoTaller/ProyectoTaller/Conexion/ConexionTaller.Context.cs
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Detalle_Reparacion> Detalle_Reparacion { get; set; }
        public virtual DbSet<Facturacion> Facturacion { get; set; }
        public virtual DbSet<Inventario_Respuesto> Inventario_Respuesto { get; set; }
        public virtual DbSet<Mecanicos> Mecanicos { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<Taller> Taller { get; set; }
        public virtual DbSet<Vehiculos> Vehiculos { get; set; }
    }
}
