//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTaller.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturacion
    {
        public int id_factura { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public Nullable<int> id_mecanico { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_taller { get; set; }
        public Nullable<int> id_vehiculo { get; set; }
        public Nullable<int> subtotal { get; set; }
        public Nullable<int> total { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Mecanicos Mecanicos { get; set; }
        public virtual Taller Taller { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
