//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTaller.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturacion
    {
        public int id { get; set; }
        public string rnc_taller { get; set; }
        public string modelo_vehiculo { get; set; }
        public string marca_vehiculo { get; set; }
        public string color_vehiculo { get; set; }
        public string nombre_servicio { get; set; }
        public string nombre_taller { get; set; }
        public string direccion_taller { get; set; }
        public string telefono_taller { get; set; }
        public Nullable<int> costo_trabajo { get; set; }
    }
}
