//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTaller.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario_Respuesto
    {
        public int id { get; set; }
        public string nombre_pieza { get; set; }
        public Nullable<int> cantidad_pieza { get; set; }
        public Nullable<int> precio_pieza { get; set; }
        public Nullable<int> cantidad_disponible { get; set; }
        public string estado_piezas { get; set; }
    }
}
