//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTaller.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mecanicos
    {
        public int id_mecanico { get; set; }
        public Nullable<int> id_taller_mecanico { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string cedula { get; set; }
        public string fecha_nacimiento { get; set; }
        public Nullable<bool> estatus { get; set; }
    
        public virtual Taller Taller { get; set; }
    }
}
