//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTaller.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string tipo_servicio { get; set; }
        public Nullable<int> costo { get; set; }
    }
}
