//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTaller.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        public int id_vehiculo { get; set; }
        public Nullable<int> id_vehiculo_cliente { get; set; }
        public string matricula { get; set; }
        public string modelo { get; set; }
        public string color { get; set; }
        public string marca { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
