//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTaller.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        public int id_vehiculo { get; set; }
        public Nullable<int> id_vehiculo_cliente { get; set; }
        public string matricula { get; set; }
        public string modelo { get; set; }
        public string color { get; set; }
        public string marca { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
