//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curiculum.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienciaLaboral
    {
        public int id_Experiencia { get; set; }
        public string Empresa { get; set; }
        public string Puesto { get; set; }
        public string FechaDeEntrada { get; set; }
        public string FechaDeSalida { get; set; }
        public string DatosComplementarios { get; set; }
        public Nullable<int> id_persona { get; set; }
    
        public virtual DatosPersonales DatosPersonales { get; set; }
    }
}
