//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curiculum.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formacion_Y_estudios
    {
        public int id_estudios { get; set; }
        public string TitulosUniversitarios { get; set; }
        public string CualCarrera { get; set; }
        public string Idiomas { get; set; }
        public string CualesIdiomas { get; set; }
        public string ConocimientosInformaticos { get; set; }
        public string CursosRealizados { get; set; }
        public Nullable<int> id_persona { get; set; }
    
        public virtual DatosPersonales DatosPersonales { get; set; }
    }
}
