//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curiculum.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fotos
    {
        public int id_fotos { get; set; }
        public byte[] Fotos1 { get; set; }
        public Nullable<int> id_persona { get; set; }
    
        public virtual DatosPersonales DatosPersonales { get; set; }
    }
}
