//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTranslogic.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class companiaproveedoras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public companiaproveedoras()
        {
            this.detalle_de_viaje = new HashSet<detalle_de_viaje>();
            this.vehiculos = new HashSet<vehiculos>();
        }
    
        public int id_compania { get; set; }
        public string nombre { get; set; }
        public string rnc { get; set; }
        public string direccion { get; set; }
        public string cantidad_Buses { get; set; }
        public Nullable<int> id_safe { get; set; }
    
        public virtual safe_journey safe_journey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_de_viaje> detalle_de_viaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehiculos> vehiculos { get; set; }
    }
}
