//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTranslogic.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_TranslogicEntities7 : DbContext
    {
        public db_TranslogicEntities7()
            : base("name=db_TranslogicEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<companiaproveedoras> companiaproveedoras { get; set; }
        public virtual DbSet<coordinacion_viaje> coordinacion_viaje { get; set; }
        public virtual DbSet<detalle_de_viaje> detalle_de_viaje { get; set; }
        public virtual DbSet<eventos> eventos { get; set; }
        public virtual DbSet<safe_journey> safe_journey { get; set; }
        public virtual DbSet<vehiculos> vehiculos { get; set; }
    }
}
