//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTranslogic.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_TranslogicEntities1 : DbContext
    {
        public db_TranslogicEntities1()
            : base("name=db_TranslogicEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<companiaproveedoras> companiaproveedoras { get; set; }
        public virtual DbSet<coordinacion_viaje> coordinacion_viaje { get; set; }
        public virtual DbSet<detalle_de_viaje> detalle_de_viaje { get; set; }
        public virtual DbSet<eventos> eventos { get; set; }
        public virtual DbSet<safe_journey> safe_journey { get; set; }
        public virtual DbSet<vehiculos> vehiculos { get; set; }
    }
}
