//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTranslogic.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class coordinacion_viaje
    {
        public int id { get; set; }
        public string fecha_hacia_evento { get; set; }
        public string fecha_hacia_casa { get; set; }
        public string tipo_transporte { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_evento { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual eventos eventos { get; set; }
    }
}
