//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTranslogic.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_de_viaje
    {
        public int id { get; set; }
        public Nullable<double> kilometros_recorridos { get; set; }
        public Nullable<double> subtotal { get; set; }
        public Nullable<double> costo_total { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_evento { get; set; }
        public Nullable<int> id_vehiculo { get; set; }
        public Nullable<int> id_compania { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual companiaproveedoras companiaproveedoras { get; set; }
        public virtual eventos eventos { get; set; }
        public virtual vehiculos vehiculos { get; set; }
    }
}
