//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTranslogic.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_de_viaje
    {
        public int id_detalle { get; set; }
        public Nullable<double> kilometros_recorridos { get; set; }
        public Nullable<double> subtotal { get; set; }
        public Nullable<double> costo_total { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_evento { get; set; }
        public Nullable<int> id_vehiculo { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual eventos eventos { get; set; }
        public virtual vehiculos vehiculos { get; set; }
    }
}
