//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTranslogic.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eventos()
        {
            this.detalle_de_viaje = new HashSet<detalle_de_viaje>();
        }
    
        public int id_evento { get; set; }
        public string nombre_evento { get; set; }
        public string ciudad_evento { get; set; }
        public string tipo_de_evento { get; set; }
        public string fecha_de_evento { get; set; }
        public Nullable<System.DateTime> fecha_registro_de_event { get; set; }
        public string fecha_hacia_evento { get; set; }
        public string fecha_hacia_casa { get; set; }
        public Nullable<int> id_cliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_de_viaje> detalle_de_viaje { get; set; }
    }
}
