//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTranslogic.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eventos()
        {
            this.detalle_de_viaje = new HashSet<detalle_de_viaje>();
        }
    
        public int id_evento { get; set; }
        public string nombre_evento { get; set; }
        public string ciudad_evento { get; set; }
        public string tipo_de_evento { get; set; }
        public string fecha_de_evento { get; set; }
        public Nullable<System.DateTime> fecha_registro_de_evento { get; set; }
        public Nullable<int> id_cliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_de_viaje> detalle_de_viaje { get; set; }
    }
}
