//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTranslogic.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehiculos()
        {
            this.detalle_de_viaje = new HashSet<detalle_de_viaje>();
        }
    
        public int id_vehiculo { get; set; }
        public string tipo_de_vehiculo { get; set; }
        public string chofer { get; set; }
        public string chofer_extra { get; set; }
        public string placa { get; set; }
        public Nullable<int> cantidad_asientas { get; set; }
        public string tipo { get; set; }
        public Nullable<double> precio_por_asiento { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<int> id_compania { get; set; }
    
        public virtual companiaproveedoras companiaproveedoras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_de_viaje> detalle_de_viaje { get; set; }
    }
}
