//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTaller.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Reparacion
    {
        public int id_detalle { get; set; }
        public Nullable<int> id_vehiculo { get; set; }
        public Nullable<int> id_inventario { get; set; }
        public Nullable<int> precio { get; set; }
        public string cantidad { get; set; }
        public Nullable<int> mano_obra { get; set; }
        public Nullable<int> id_servicio { get; set; }
    
        public virtual Inventario_Respuesto Inventario_Respuesto { get; set; }
        public virtual Servicios Servicios { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
