//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aula
    {
        public int id { get; set; }
        public Nullable<int> taller_id { get; set; }
        public string NombreAula { get; set; }
        public string TipoAula { get; set; }
        public string CantidadDeEstudiante { get; set; }
    
        public virtual taller taller { get; set; }
    }
}
